#name: grakn-pytorch-geometric
#channels:
#  - conda-forge
#  - pytorch
#  - defaults
#dependencies:
#  - python=3.7
#  - pip
#  - networkx
#  - matplotlib
#  - pandas
#  - pytorch=1.7.0
#  - pytorch-lightning
#  - pip:
#    - -e .
#    - -e ../kglib
#    - pytest
#    - grakn-client
#    - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
#    - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
#    - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
#    - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
#    - torch-geometric
