# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.1.0.post16+g7c6c043.d20210517'
version_tuple = (0, 1, 0, 'post16+g7c6c043', 'd20210517')
